- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: Copy jar files to prod
      copy: src=discovery-service-1.0.jar dest=/usr/local/src/tmpcandelete
          owner=root group=root mode=0644
    - name: start jar
      shell:  nohup java -jar /usr/local/src/tmpcandelete/discovery-service-1.0.jar  &

