node {

    stage('Pull source code') {
       git 'https://github.com/yingxx26/notebook-k8s.git'
    }
     dir('discovery-service') {
            //构建 Maven
            stage('Build and UI test'){
                sh ' mvn package -Dmaven.test.skip=true'
            }
        }
    dir('notebook-service') {
        //构建 Maven
        stage('Build and UI test'){
            sh ' mvn package -Dmaven.test.skip=true'
        }
    }
    dir('Chapter-8') {
        //部署 notebook.jar to remote server
        stage('Ansible Deploy to remote server2'){
            sh 'cp ../discovery-service/target/discovery-service-1.0.jar ./'
            sh 'cp ../notebook-service/target/notebook-service-1.0.jar ./'
            sh 'su - root c "ansible-playbook notebook-all-playbook.yml"'
        }
    }
 }
